### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by willyyyyy1** [kevinkouketsu/WYD2Bot#2]
hello
I try setup Visual Studio 2017 vs_Professional
and i open your project
but when i open 
the error list  show a lot of message
detail
[error.txt](https://github.com/kevinkouketsu/WYD2Bot/files/2387255/error.txt)
![error](https://user-images.githubusercontent.com/16967188/45604215-ca665480-ba64-11e8-8b52-7abfe443843e.jpg)
why??

**Comment by kevinkouketsu** [comment]
You opened with a wrong application. You used Visual Studio BLEND.
Install VS Community if you don't have the key, it's free. Open .sln file with Visual Studio, not VS Blend.

**Comment by willyyyyy1** [comment]
get it  thank you
