### ISSUE TITLE
EU TENHO UM BUG

### ISSUE THREAD

**Issue by https-igor** [kevinkouketsu/WYD2Bot#3]
É aqui que mudo o ip e porta?

Esta aparecendo esse erro. E como faco para descobrir qual é o ip do wyd que quero usar?

http://prntscr.com/kveko3

**Comment by https-igor** [comment]
43 9 99143631

**Comment by okumal** [comment]
Quanto cobra, para me dar uma consultoria?

**Comment by kevinkouketsu** [comment]
O parametro errado seria uma cadeia de char(string), seria o ip em questão, como por exemplo:
"127.0.0.1".

O IP consta no serverlist de cada servidor. 

Isto não é um issue já que não consta nenhum erro, por isso irei fechá-lo. Caso encontre um erro, pode postar aqui que irei ajudá-lo. Minha sugestão é que va´na WebCheats e poste suas dúvidas lá já que não são referentes ao meu código em si.
