### ISSUE TITLE
can not connection

### ISSUE THREAD

**Issue by willyyyyy1** [kevinkouketsu/WYD2Bot#4]
I want  use for http://origins.vibrant3g.com/index.asp
I Set
Server::Connect
	service->sin_addr.s_addr 	= inet_addr("164.132.24.96");
	service->sin_port		= htons(8281);
SendRequestLogin
	packet.CliVer = 7000;
and
compile  with no error
i had download AttributeMap.dat, HeightMap.dat, ItemList.csv, SkillData.csv
and put the same folder
![image](https://user-images.githubusercontent.com/16967188/45797478-52a06000-bcd8-11e8-918a-5841061a23f0.png)
i use WYD2Bot.exe
and in put login / password / numeric password
![image](https://user-images.githubusercontent.com/16967188/45797546-a90d9e80-bcd8-11e8-96bc-663d682f8be3.png)
but it show  disconnection
maybe which  step wrong?
i try the different IP is 164.132.24.100   but it's  the same show  disconnection

**Comment by https-igor** [comment]
Eu tenho o mesmo erro, heeeeelp

**Comment by kevinkouketsu** [comment]
To connect on Asgard you have to make two implementations: TimeStamp system, hashkey system and maybe anothers minors implementations.

Just with this project you can not do that.

Em 21 de set de 2018, à(s) 00:22, willyyyyy1 <notifications@github.com<mailto:notifications@github.com>> escreveu:


Reopened #4<https://github.com/kevinkouketsu/WYD2Bot/issues/4>.

**Comment by https-igor** [comment]
E sobre esse wyd: http://wydnordicwar.com/
Pode ajudar usar nesse wyd?

**Comment by kevinkouketsu** [comment]
Pessoal, eu dou suporte a correções e problemas não a alterar da sua forma.
O código ta aí, use-o.


Em 21 de set de 2018, à(s) 08:22, okumal <notifications@github.com<mailto:notifications@github.com>> escreveu:


E sobre esse wyd: http://wydnordicwar.com/
Pode ajudar usar nesse wyd?
